Add assoc
OnlyReFLeX/test-guru pull request #12
Opened 2018-02-25 17:19 UTC by OnlyReFLeX

2018-02-25 18:23 UTC, iBublik requested changes

2018-02-25 18:23 UTC, iBublik commented on app/models/test.rb
> +  belongs_to :author, class_name: 'User'
Ассоциации лучше по типу группировать (`belongs_to/has_many/has_one`), а не вперемешку - так код легче читать

2018-02-25 18:23 UTC, iBublik commented on app/models/user.rb
> +  has_many :my_tests, class_name: 'Test', foreign_key: 'author_id'
Я бы назвал `passed_tests` - это более обезличенно, что в контексте кода лучше читается

2018-02-26 15:39 UTC, psylone approved these changes

2018-02-26 15:39 UTC, psylone commented on app/models/user.rb
> +  has_many :passed_tests, class_name: 'Test', foreign_key: 'author_id'
Скорее `authored_tests`, это же тесты которые пользователь создал.

2018-02-26 15:59 UTC, merged