scopes and validation
OnlyReFLeX/test-guru pull request #13
Opened 2018-02-27 11:54 UTC by OnlyReFLeX

2018-02-27 12:11 UTC, psylone requested changes

2018-02-27 12:11 UTC, psylone commented on app/models/test.rb
> +  validates :title, uniqueness: { scope: :level }
Нужно добавить составной индекс на уникальность.

2018-02-27 12:11 UTC, psylone commented on app/models/test.rb
> +  scope :category_by_title, lambda { |title|
Почему везде литерал, а здесь метод `lambda`?

2018-02-27 12:11 UTC, psylone commented on app/models/test.rb
>          .pluck('tests.title')
`pluck` стоит вынести за пределы скоупа, поскольку предполагается что скоуп-методы могут вызываться в цепочке с другими скоуп-методами и/или методами ActiveRecord. Получится нечто вроде: `Test.by_category(category_title).pluck(:title)`.

2018-02-27 12:11 UTC, psylone commented on app/models/user.rb
> +
Метод ниже `open_tests_by_level` в принципе уже не нужен. Мы можем написать: `user.tests.level(level)`.

2018-02-27 12:11 UTC, psylone commented on app/models/test.rb
> +  scope :level, ->(level) { where(level: level) }
👍

2018-02-27 13:29 UTC, OnlyReFLeX commented on app/models/test.rb
> +  scope :category_by_title, lambda { |title|
Rubocop считает что лучше использовать lambda в многострочных блоках

2018-02-27 19:21 UTC, merged

2018-02-27 21:58 UTC, psylone commented on app/models/test.rb
> +  scope :category_by_title, lambda { |title|
Я бы не стал на 100% доверять роботу.

2018-02-28 09:40 UTC, OnlyReFLeX commented on app/models/test.rb
> +  scope :category_by_title, lambda { |title|
Понял, принял