Create views
OnlyReFLeX/test-guru pull request #15
Opened 2018-03-02 19:04 UTC by OnlyReFLeX

2018-03-03 14:21 UTC, iBublik commented on app/helpers/application_helper.rb
> +    Time.now.year
Здесь лучше использовать `Time.current` вместо `Time.now`. Первый вариант учитывает таймзону, установленную в приложении, второй опирается на системную таймзону. Это может привести к трудноисправимым багам

2018-03-03 14:21 UTC, iBublik commented on app/views/questions/_form.html.erb
> +<%= form.label :body %>
Соблюдай уровень отступов, так код читается проще, и привыкать нужно сразу к хорошему. В некоторых шаблонизаторах (например, Slim), правильный уровень отступов важен для создания корректной разметки

2018-03-03 14:21 UTC, iBublik commented on app/views/questions/_form.html.erb
> +<%= form_with model: [@test, @question], local: true do |form| %>
Паритиалы предполагают переиспользование, поэтому лучше в них использовать _только_ локальные переменные. Иначе будет очень трудно разобраться, откуда вообще пришли данные, где они были проинициализированы

2018-03-04 17:48 UTC, psylone requested changes

2018-03-04 17:48 UTC, psylone commented on app/controllers/questions_controller.rb
>    def index
Этот метод более не нужен поскольку вопросы выводятся на странице просмотра теста.

2018-03-04 17:48 UTC, psylone commented on app/helpers/application_helper.rb
> +    link_to repo, "https://github.com/#{author}/#{repo}"
Ссылка должна открываться в новой вкладке.

2018-03-04 17:48 UTC, psylone commented on app/helpers/questions_helper.rb
> +    if @question.new_record?
Будет лучше передавать объект вопроса как параметр метода `question_header`. Это сделает код менее зависимым и позволит в дальнейшем тестировать его лучше.

2018-03-04 17:48 UTC, psylone commented on app/views/layouts/application.html.erb
> +    <footer>
Стоит вынести футер во фрагмент представления.

2018-03-04 17:48 UTC, psylone commented on app/views/layouts/application.html.erb
> +      <p><%= link_to 'Учебный проект в онлайн-школе Thinknetica', 'http://thinknetica.com/' %></p>
Ссылка в новой вкладке.

2018-03-04 17:48 UTC, psylone commented on app/views/tests/_test.html.erb
> +<h3><%= link_to "Тест #{test.title}", test %></h3>
Как мы будем осуществлять действия над тестом?

2018-03-04 17:48 UTC, psylone commented on app/views/tests/_test.html.erb
> +<h3><%= link_to "Тест #{test.title}", test %></h3>
Также по заданию необходимо выводить в списке тестов количество вопросов для каждого теста.

2018-03-04 18:35 UTC, psylone commented
Опция [`shallow`](https://github.com/OnlyReFLeX/test-guru/blob/master/config/routes.rb#L2) должна быть у ресурса вопросов.

2018-03-05 16:37 UTC, iBublik commented on app/controllers/tests_controller.rb
> +  def index
Отделяй пустрой строкой код, выполняемый на уровне классов, от объявления методов

2018-03-05 16:37 UTC, iBublik commented on config/routes.rb
> +    resources :questions, shallow: true
Исключи из роутинга несуществующие точки входа (index страница вопросов). Иначе у тебя будет ошибка на уровне приложения, если кто-то постучится по эндпоинту /tests/1/question - роутинг отработает как надо, а вьюхи под него не будет, что вызовет 500 ошибку

2018-03-05 18:09 UTC, OnlyReFLeX commented on config/routes.rb
> +    resources :questions, shallow: true
@iBublik вы проверили задание но на teachbase у меня еще стоит на рассмотрение

2018-03-05 22:38 UTC, psylone approved these changes

2018-03-05 22:47 UTC, merged